"""Recruitment_form

Revision ID: 505fc489cc5b
Revises: 0f170b36b5bb
Create Date: 2025-04-19 03:45:54.446728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505fc489cc5b'
down_revision = '0f170b36b5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicants')
    # ### end Alembic commands ###
