"""ready to go

Revision ID: 5457f9c2d16e
Revises: fb4c66314ddc
Create Date: 2025-06-27 07:35:48.015056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5457f9c2d16e'
down_revision = 'fb4c66314ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_type', sa.String(length=20), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('apply_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('apply_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('return', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.drop_table('applicants')
    op.drop_table('personal_application')
    op.drop_table('organization_application')
    op.drop_table('branch')
    # ### end Alembic commands ###
