"""empty message

Revision ID: 7d46f3f4f96c
Revises: 52ae36778b2a
Create Date: 2025-04-21 05:07:40.790245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d46f3f4f96c'
down_revision = '52ae36778b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_type', sa.String(length=20), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('apply_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('apply_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_application')
    op.drop_table('organization_application')
    # ### end Alembic commands ###
