"""recycle store table

Revision ID: b75f2d9d362f
Revises: 5e892e7fb7e5
Create Date: 2025-04-18 20:56:48.938228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75f2d9d362f'
down_revision = '5e892e7fb7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycle_store',
    sa.Column('branch_name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('bus_hour', sa.String(length=128), nullable=False),
    sa.Column('cycle_items', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('branch_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recycle_store')
    # ### end Alembic commands ###
